# Generated by Django 2.2.8 on 2019-12-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0)),
                ('last', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OwnPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studentId', models.CharField(max_length=10, unique=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Prize')),
            ],
        ),
    ]
