# Generated by Django 2.2.8 on 2019-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studentId', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ownprize',
            name='studentId',
            field=models.CharField(max_length=10),
        ),
    ]
